name: CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        emacs_version:
          - 27.2
          - 28.2

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run tests
        run: |
          cat <<EOF > init.el
          (require 'package)
          (package-refresh-contents)
          (package-install 'compat)
          EOF
          emacs -Q --batch -L . -l init.el -l selrgn-tests.el -f ert-run-tests-batch-and-exit
