name: CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        emacs_version:
          - 27.2
          - 28.2

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run tests
        run: |
          cat <<EOF > init.el
          (require 'package)
          (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
          (package-refresh-contents)
          (package-install 'compat)
          (package-install 'undercover)

          (when (require 'undercover nil t)
            (undercover "*.el" (:report-format 'codecov) (:send-report nil)))
          EOF
          cat init.el
          emacs --batch -L . -l init.el -l selrgn-tests.el -f ert-run-tests-batch-and-exit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
