name: CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        emacs_version:
          - 27.2
          - 28.2
          - 29.4
          - 30.2

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Lint
        run: eldev lint

      - name: Run tests
        run: eldev -dtT test -u codecov,dontsend

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
